package dev.example.mapi.internal.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.List;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class MapiConfigTest {

    private static final Logger LOG = LoggerFactory.getLogger(MapiConfigTest.class);

    @TempDir
    Path configDir;

    @TempDir
    Path gameDir;

    private MapiConfig load(Map<String, String> env) {
        return MapiConfig.load(configDir, gameDir, env, LOG);
    }

    private Path configFile() {
        return configDir.resolve(MapiConfig.CONFIG_FILE_NAME);
    }

    private Path defaultTokenFile() {
        return gameDir.resolve(MapiConfig.DATA_DIR_NAME).resolve(MapiConfig.TOKEN_FILE_NAME);
    }

    private void writeToml(String content) throws IOException {
        Files.writeString(configFile(), content, StandardCharsets.UTF_8);
    }

    @Test
    void templateIsGeneratedAutomaticallyWithDefaults() throws IOException {
        MapiConfig config = load(Map.of());
        assertFalse(config.httpEnabled(), "default template must leave the API disabled");
        assertTrue(Files.isRegularFile(configFile()), "mapi.toml must be created on first start");
        String text = Files.readString(configFile(), StandardCharsets.UTF_8);
        assertTrue(text.startsWith("[http]"), "TOML table header expected: " + text);
        assertTrue(text.contains("enabled = false"), text);
        assertTrue(text.contains("port = 25586"), text);
        assertTrue(text.contains("http.port"), "dotted key must parse back");
        assertTrue(text.contains("# Enable the local HTTP API"), "comments expected");
        // Round trip: parsing the generated template yields the same defaults.
        assertEquals(25586, config.httpPort());
        assertEquals("mapi-25586", config.instanceId());
        assertEquals(30, config.discoveryHeartbeatSeconds());
        assertEquals(2, config.commandPermissionLevel());
    }

    @Test
    void tomlValuesAreHonored() throws IOException {
        writeToml("""
                [http]
                enabled = true
                port = 20000
                rateLimitPerMinute = 5
                instanceId = "mx-toml-1"
                scopes = "observe, world.read"
                commandPermissionLevel = 3

                [reflection]
                enabled = true
                """);
        MapiConfig config = load(Map.of());
        assertTrue(config.httpEnabled());
        assertEquals(20000, config.httpPort());
        assertEquals(5, config.rateLimitPerMinute());
        assertEquals("mx-toml-1", config.instanceId());
        assertTrue(config.reflectionEnabled());
        assertEquals(3, config.commandPermissionLevel());
        assertTrue(config.scopes().contains("world.read"));
        assertFalse(config.scopes().contains("unsafe.execute"));
    }

    @Test
    void envOverridesToml() throws IOException {
        writeToml("[http]\nenabled = true\nport = 20000\n");
        MapiConfig config = load(Map.of("MAPI_HTTP_PORT", "20001"));
        assertEquals(20001, config.httpPort());
    }

    @Test
    void legacyPropertiesFileIsMigrated() throws IOException {
        Files.writeString(configDir.resolve(MapiConfig.LEGACY_CONFIG_FILE_NAME),
                "http.enabled=true\nhttp.port=20002\nhttp.token=1234567890abcdefgh\n",
                StandardCharsets.UTF_8);
        MapiConfig config = load(Map.of());
        assertTrue(config.httpEnabled());
        assertEquals(20002, config.httpPort());
        assertEquals("1234567890abcdefgh", config.httpToken());
        // No TOML is fabricated while the legacy file exists (it remains the
        // file of record until the operator converts it).
        assertFalse(Files.isRegularFile(configFile()));
    }

    @Test
    void missingTokenIsAutoGeneratedToFile() throws IOException {
        writeToml("[http]\nenabled = true\n");
        MapiConfig config = load(Map.of());
        assertTrue(config.httpEnabled());
        assertNotNull(config.httpToken());
        assertTrue(config.httpToken().length() >= MapiConfig.MIN_TOKEN_LENGTH);
        assertEquals(config.httpToken(), Files.readString(defaultTokenFile(), StandardCharsets.UTF_8).trim());
        if (defaultTokenFile().getFileSystem().supportedFileAttributeViews().contains("posix")) {
            Set<PosixFilePermission> perms = Files.getPosixFilePermissions(defaultTokenFile());
            assertEquals(PosixFilePermissions.fromString("rw-------"), perms,
                    "token file must be owner-restricted");
        }
        assertFalse(hasLeftoverTempFiles(defaultTokenFile().getParent()), "temp files must be cleaned up");
    }

    @Test
    void existingTokenFileIsReused() throws IOException {
        writeToml("[http]\nenabled = true\n");
        Files.createDirectories(defaultTokenFile().getParent());
        Files.writeString(defaultTokenFile(), "token-from-file-0123456789\n", StandardCharsets.UTF_8);
        assertEquals("token-from-file-0123456789", load(Map.of()).httpToken());
    }

    @Test
    void envTokenWinsOverTokenFile() throws IOException {
        writeToml("[http]\nenabled = true\n");
        Files.createDirectories(defaultTokenFile().getParent());
        Files.writeString(defaultTokenFile(), "token-from-file-0123456789\n", StandardCharsets.UTF_8);
        assertEquals("env-token-0123456789", load(Map.of("MAPI_HTTP_TOKEN", "env-token-0123456789")).httpToken());
    }

    @Test
    void malformedTomlIsRefused() throws IOException {
        writeToml("[http\nenabled = true\n");
        assertThrows(MapiConfigException.class, () -> load(Map.of()));
        writeToml("http.enabled = maybe\n");
        assertThrows(MapiConfigException.class, () -> load(Map.of()));
        writeToml("[http]\nenabled = true\nport = \"text\"\n");
        assertThrows(MapiConfigException.class, () -> load(Map.of()));
    }

    @Test
    void unknownKeysAreIgnoredWithDefaults() throws IOException {
        writeToml("[http]\nenabled = true\nfutureKey = 1\n");
        MapiConfig config = load(Map.of());
        assertTrue(config.httpEnabled());
        assertEquals(25586, config.httpPort());
    }

    @Test
    void shortTokenFromTomlIsRefused() throws IOException {
        writeToml("[http]\nenabled = true\ntoken = \"short\"\n");
        MapiConfigException e = assertThrows(MapiConfigException.class, () -> load(Map.of()));
        assertTrue(e.getMessage().contains("16"));
    }

    @Test
    void instanceIdIsSanitized() throws IOException {
        writeToml("[http]\ninstanceId = \"My Mod!_2.\"\n");
        assertEquals("my-mod-2", load(Map.of()).instanceId());
        writeToml("[http]\ninstanceId = \"!!!\"\n");
        assertEquals("mapi-25586", load(Map.of()).instanceId());
    }

    @Test
    void invalidPortAndRateLimitAreRefused() throws IOException {
        writeToml("[http]\nport = 70000\n");
        assertThrows(MapiConfigException.class, () -> load(Map.of()));
        writeToml("[http]\nport = abc\n");
        assertThrows(MapiConfigException.class, () -> load(Map.of()));
        writeToml("[http]\nrateLimitPerMinute = 0\n");
        assertThrows(MapiConfigException.class, () -> load(Map.of()));
        writeToml("[http]\nportFallback = 99\n");
        assertThrows(MapiConfigException.class, () -> load(Map.of()));
    }

    @Test
    void tokenFingerprintIsStableAndShort() {
        assertEquals(MapiConfig.fingerprint("abc"), MapiConfig.fingerprint("abc"));
        assertEquals(12, MapiConfig.fingerprint("abc").length());
        assertTrue(MapiConfig.fingerprint("abc").chars().allMatch(c
                -> Character.isDigit(c) || (c >= 'a' && c <= 'f')));
    }

    private static boolean hasLeftoverTempFiles(Path dir) throws IOException {
        if (dir == null || !Files.isDirectory(dir)) {
            return false;
        }
        try (var files = Files.list(dir)) {
            return files.anyMatch(p -> p.getFileName().toString().contains(".tmp-"));
        }
    }
}
