package dev.example.mapi.internal.config;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.attribute.PosixFilePermission;
import java.nio.file.attribute.PosixFilePermissions;
import java.util.Map;
import java.util.Set;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

class MapiConfigTest {

    private static final Logger LOG = LoggerFactory.getLogger(MapiConfigTest.class);

    @TempDir
    Path configDir;

    @TempDir
    Path gameDir;

    private MapiConfig load(Map<String, String> env) {
        return MapiConfig.load(configDir, gameDir, env, LOG);
    }

    private Path defaultTokenFile() {
        return gameDir.resolve(MapiConfig.DATA_DIR_NAME).resolve(MapiConfig.TOKEN_FILE_NAME);
    }

    @Test
    void defaultsDisableHttp() {
        MapiConfig config = load(Map.of());
        assertFalse(config.httpEnabled());
        assertEquals(MapiConfig.DEFAULT_PORT, config.httpPort());
        assertNull(config.httpToken());
        assertEquals(MapiConfig.DEFAULT_RATE_LIMIT, config.rateLimitPerMinute());
        assertEquals("mapi-" + MapiConfig.DEFAULT_PORT, config.instanceId());
        assertEquals(gameDir.resolve(MapiConfig.DATA_DIR_NAME).resolve(MapiConfig.TOKEN_FILE_NAME),
                config.tokenFile());
    }

    @Test
    void envOverridesFile() throws IOException {
        writeFile("http.enabled=true\nhttp.port=20000\nhttp.token=1234567890abcdefgh\n");
        MapiConfig config = load(Map.of("MAPI_HTTP_PORT", "20001"));
        assertTrue(config.httpEnabled());
        assertEquals(20001, config.httpPort());
        assertEquals("1234567890abcdefgh", config.httpToken());
    }

    @Test
    void tokenFromEnvWhenFileMissing() {
        MapiConfig config = load(Map.of("MAPI_HTTP_ENABLED", "true", "MAPI_HTTP_TOKEN", "tok-0123456789abcdef"));
        assertTrue(config.httpEnabled());
        assertEquals("tok-0123456789abcdef", config.httpToken());
    }

    @Test
    void missingTokenIsAutoGeneratedToFile() throws IOException {
        MapiConfig config = load(Map.of("MAPI_HTTP_ENABLED", "true"));
        assertTrue(config.httpEnabled());
        assertNotNull(config.httpToken());
        assertTrue(config.httpToken().length() >= MapiConfig.MIN_TOKEN_LENGTH,
                "generated token must meet the length policy");
        assertEquals(config.httpToken(), Files.readString(defaultTokenFile(), StandardCharsets.UTF_8).trim());
        assertTrue(config.httpToken().equals(config.httpToken().trim()));
        if (defaultTokenFile().getFileSystem().supportedFileAttributeViews().contains("posix")) {
            Set<PosixFilePermission> perms = Files.getPosixFilePermissions(defaultTokenFile());
            assertEquals(PosixFilePermissions.fromString("rw-------"), perms,
                    "token file must be owner-restricted");
        }
        assertFalse(hasLeftoverTempFiles(defaultTokenFile().getParent()),
                "temp files must be cleaned up");
    }

    private static boolean hasLeftoverTempFiles(Path dir) throws IOException {
        if (dir == null || !Files.isDirectory(dir)) {
            return false;
        }
        try (var files = Files.list(dir)) {
            return files.anyMatch(p -> p.getFileName().toString().contains(".tmp-"));
        }
    }

    @Test
    void existingTokenFileIsReused() throws IOException {
        Files.createDirectories(defaultTokenFile().getParent());
        Files.writeString(defaultTokenFile(), "token-from-file-0123456789\n", StandardCharsets.UTF_8);
        MapiConfig config = load(Map.of("MAPI_HTTP_ENABLED", "true"));
        assertEquals("token-from-file-0123456789", config.httpToken());
    }

    @Test
    void envTokenWinsOverTokenFile() throws IOException {
        Files.createDirectories(defaultTokenFile().getParent());
        Files.writeString(defaultTokenFile(), "token-from-file-0123456789\n", StandardCharsets.UTF_8);
        MapiConfig config = load(Map.of("MAPI_HTTP_ENABLED", "true", "MAPI_HTTP_TOKEN", "env-token-0123456789"));
        assertEquals("env-token-0123456789", config.httpToken());
    }

    @Test
    void tokenFileKeySupportsRelativeAndAbsolutePaths() throws IOException {
        MapiConfig relative = load(Map.of("MAPI_HTTP_ENABLED", "true", "MAPI_HTTP_TOKEN_FILE", "custom/tok"));
        assertEquals(gameDir.resolve("custom").resolve("tok").normalize(), relative.tokenFile());
        assertNotNull(relative.httpToken(), "custom token file must be generated when missing");
        assertTrue(Files.isRegularFile(gameDir.resolve("custom").resolve("tok")));

        Path absolute = gameDir.resolve("abs-token");
        MapiConfig abs = load(Map.of("MAPI_HTTP_ENABLED", "true", "MAPI_HTTP_TOKEN_FILE",
                absolute.toString()));
        assertEquals(absolute, abs.tokenFile());
    }

    @Test
    void shortTokenInTokenFileIsRefused() throws IOException {
        Files.createDirectories(defaultTokenFile().getParent());
        Files.writeString(defaultTokenFile(), "short", StandardCharsets.UTF_8);
        MapiConfigException e = assertThrows(MapiConfigException.class,
                () -> load(Map.of("MAPI_HTTP_ENABLED", "true")));
        assertTrue(e.getMessage().contains("16"));
    }

    @Test
    void instanceIdIsSanitized() {
        assertEquals("my-mod-2", load(Map.of("MAPI_INSTANCE_ID", "My Mod!_2.")).instanceId());
        assertEquals("abc", load(Map.of("MAPI_INSTANCE_ID", "  ABC ")).instanceId());
        String longId = "a".repeat(40);
        assertEquals("a".repeat(32), load(Map.of("MAPI_INSTANCE_ID", longId)).instanceId());
        assertEquals("mapi-25586", load(Map.of("MAPI_INSTANCE_ID", "!!!")).instanceId(),
                "unusable ids fall back to the default instead of failing the game");
    }

    @Test
    void tokenWithoutHttpEnabledIsAllowed() {
        MapiConfig config = load(Map.of("MAPI_HTTP_TOKEN", "short"));
        assertFalse(config.httpEnabled());
        assertEquals("short", config.httpToken());
    }

    @Test
    void invalidPortAndRateLimitAreRefused() {
        assertThrows(MapiConfigException.class, () -> load(Map.of("MAPI_HTTP_PORT", "0")));
        assertThrows(MapiConfigException.class, () -> load(Map.of("MAPI_HTTP_PORT", "70000")));
        assertThrows(MapiConfigException.class, () -> load(Map.of("MAPI_HTTP_PORT", "abc")));
        assertThrows(MapiConfigException.class, () -> load(Map.of("MAPI_HTTP_RATE_LIMIT_PER_MINUTE", "0")));
    }

    @Test
    void invalidBooleanIsRefused() {
        assertThrows(MapiConfigException.class, () -> load(Map.of("MAPI_HTTP_ENABLED", "yes-please")));
    }

    @Test
    void missingConfigFileIsFine() {
        MapiConfig config = load(Map.of());
        assertFalse(config.httpEnabled());
    }

    @Test
    void valuesAndKeysAreTrimmed() throws IOException {
        writeFile("http.enabled = true \nhttp.token=  verylongtokenvalue123\n");
        MapiConfig config = load(Map.of());
        assertTrue(config.httpEnabled());
        assertEquals("verylongtokenvalue123", config.httpToken());
    }

    @Test
    void tokenFingerprintIsStableAndShort() {
        assertEquals(MapiConfig.fingerprint("abc"), MapiConfig.fingerprint("abc"));
        assertEquals(12, MapiConfig.fingerprint("abc").length());
        assertTrue(MapiConfig.fingerprint("abc").chars().allMatch(c
                -> Character.isDigit(c) || (c >= 'a' && c <= 'f')));
    }

    private void writeFile(String content) throws IOException {
        Files.writeString(configDir.resolve(MapiConfig.CONFIG_FILE_NAME), content, StandardCharsets.UTF_8);
    }
}
