package dev.example.mapi.neoforge;

import dev.example.mapi.internal.MapiBootstrap;
import net.neoforged.bus.api.IEventBus;
import net.neoforged.fml.ModContainer;
import net.neoforged.fml.common.Mod;

/**
 * NeoForge entrypoint. Deliberately thin: forwards to the loader-neutral
 * bootstrap. All real work lives in the common module.
 */
@Mod(MapiNeoForge.MOD_ID)
public final class MapiNeoForge {

    /**
     * The MAPI mod id ({@value}).
     */
    public static final String MOD_ID = "mapi";

    /**
     * NeoForge entrypoint invoked when the mod container is constructed,
     * before any server can start.
     *
     * @param modEventBus mod-specific event bus (unused; server events are
     *                    registered on the game bus by the platform adapter)
     * @param modContainer this mod's container (unused today, kept for future
     *                     configuration integration)
     */
    public MapiNeoForge(IEventBus modBus, ModContainer modContainer) {
        MapiBootstrap.initialize(new NeoForgePlatform());
        // Loader-native TOML config (mapi-common.toml, generated by FML):
        // HTTP starts on the config load event with those values.
        dev.example.mapi.client.neoforge.MapiNeoConfig.register(modContainer, modBus,
                net.neoforged.fml.loading.FMLPaths.GAMEDIR.get(),
                MapiBootstrap::runtime);
        // Client-only code is isolated under dev.example.mapi.client.*; the
        // branch plus lazy classloading keep the class from loading on
        // dedicated servers (NeoForge 26.2 no longer strips @OnlyIn members
        // and warns when the annotation is present, so it is not used).
        if (net.neoforged.fml.loading.FMLEnvironment.getDist().isClient()) {
            dev.example.mapi.client.neoforge.NeoForgeClientOps.register();
        }
    }
}
